<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [2]:

def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting("Super Man")

'Hello Super Man!'

In [4]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [5]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

In [6]:
basic_stats([1, 2, 3, 4, 5, 6])

(1, 6, 3.5)

### 1.2 Named functions that don’t return

In [3]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


### 1.3 Anonymous functions

In [11]:
my_short_function = lambda cry: f"Hello {cry}!"

In [13]:
my_short_function(cry="Super Man")

'Hello Super Man!'

In [1]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [2]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [17]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [20]:
greeting('Me')

'Hello Me!'

In [21]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


In [23]:
?print

## 2 The importance of functions?

### 2.1 An argument for functions

In [3]:
print('Please')

Please


### 2.2 A word of caution

In [4]:
print('Help Me')

Help Me


## Exercise 1 :  Do you know why?

In [8]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting('Batman')

'Hello Batman! So, nice to meet you!'

# Koi's explanation
The function, *greeting(name)* was defined as a conditional argument such that **if** 'Batman' was input into the function, the trigger immediately after the conditional is 'true', in this case, *'Hello Batman! So, nice to meet you!'* is returned and the function ends and the second portion of the function is not activated. However, **if** 'Batman' was not input and the conditional is false, the statement is ignored and thus 'Hello <Input>' is returned.

## Exercise 2 :  Calculator functions

In [41]:
def add(x, y):
    return x + y
def subtract(x, y):
    return x - y
def multiply(x, y):
    return x * y
def divide(x, y):
    if type(y) == int:
        if y == 0:
            return 'Math Error dumbass!'
        else:
            return x / y 
    if type(y) == np.ndarray:
        z = len(y)
        i = 0
        c=[]
        while i < z:
            if y[i] != 0:
                c.append(x[i]/y[i])
            else:
                c.append('Math Error')
            i += 1
        return c

In [44]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])

add(x, y)

array([100, 100, 100, 100,  27])

In [12]:
subtract(x, y)

array([-28, -32, -12,  52, -46])

In [13]:
multiply(x, y)

array([2304, 2244, 2464, 1824, 1971])

In [45]:
divide(x, y)

[0.5625,
 0.5151515151515151,
 0.7857142857142857,
 3.1666666666666665,
 'Math Error']

In [40]:
def divide(x, y):
    for i, numbers in enumerate(y):
        if numbers == 0:
            return 'MATH ERROR'
        else:
            return x / y
divide (1, 0)


TypeError: 'int' object is not iterable

## Exercise 3 :  max_info() with NumPy

In [46]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

In [51]:
def max_info(numbers):
    return(np.max(numbers), np.argmax(numbers))


In [52]:
max_info(numbers)

(83, 2)