<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [2]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [3]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [4]:
print(py_real_names[0])

Natasha Romanoff


In [6]:
print(py_super_names[1])

Iron Man


In [7]:
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.

Doctor Strange


In [8]:
print(py_super_names[-1])   # Reverse indexing

Doctor Strange


### 1.3 Accessing data from a dictionary

In [14]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Stephen Strange"])

Doctor Strange


In [17]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [18]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [25]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
print(py_superhero_info[0])

['Natasha Romanoff', 'Black Widow']


## 2 Lists vs. Arrays

### 2.1 Size

In [29]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
print(py_list_2d)

[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [10, 'J']]


In [30]:
len(py_list_2d)

10

In [32]:
len(np_array_2d)

10

In [31]:
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [33]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [36]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [35]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [37]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [2]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]
py_list_1 + py_list_2


[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [4]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [7]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [10]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [14]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)   
py_list == 3

False

In [15]:
np_array == 3

array([False, False,  True, False, False])

In [16]:
np_array > 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

## Exercise 1 :  Total recall?

1. a. Both lists and arrays store data
1. b. Both lists and arrays can have more than 1 dimension

2. a. Arrays are unable to store more than 1 data type at a time while lists can
2. b. Adding lists together will increase the number of data points in the list whilst adding arrays together will result in the sum of data at each point in the array.

3. A dictionary stores information about data which can be retrived in one way when needed.

## Exercise 2 :  Index me

In [23]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])                    # Prints 'a1'
print(py_list[2])                    # Prints 'c3'
print(py_list[4])                    # Prints 'e5'
print(py_list[6])                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'
odd = (py_list[0], py_list[2], py_list [4], py_list[6], py_list[8])
print(odd)

a1
c3
e5
g7
i9
('a1', 'c3', 'e5', 'g7', 'i9')


## Exercise 3 :  Capitalise Heros

In [29]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()  
print(superhero_info['Tony Stark'])
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper

IRON MAN


In [34]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

def up(name):
    superhero_info[name] = superhero_info[name].upper()                  
up('Natasha Romanoff')
print(superhero_info['Natasha Romanoff'])

BLACK WIDOW


## Exercise 4 :  How many ones

In [41]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]  
import numpy as np
len(numbers)
np_array = np.array(numbers)
sum(np_array == 1)



9