<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [5]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array

x[2:]

array(['c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [9]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)
np_array[my_mask]

[False False False  True  True  True  True  True  True  True]


array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
def hello(name):
    if name == "Batman" or name == "Black Widow":
        print(f"Hello {name.upper()}!")
    else:
        print("Hello",name.lower(),'!')
hello('Batman')

Hello BATMAN!


In [19]:
def hello(name):
  if name == "Batman" or  "Black Widow":
    print(f"Hello {name.upper()}!")
  else:
    print(f"Hello {name.lower()}!")
hello('James')

Hello JAMES!


In [26]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[(np_array<3) | (np_array>8)]


array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [27]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [28]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [29]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [34]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [36]:
np_array_2d[1:3, 0]

array(['2', '3'], dtype='<U11')

### 1.4 Indexing & Slicing 2D Arrays

In [45]:
import numpy as np
test = np.array([1, 2, 3, 4, 5])
test + 1

array([2, 3, 4, 5, 6])

In [38]:
np_array_2d[0:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [53]:
x = []
y = 0
while  y< 10:
    y += 1
    x.append(y)   
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [54]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [55]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

## 2 Some loose ends

### 2.1 Tuples

In [58]:
a=(1, 2, 3)     # Define tuple
print(a[0])


1


### 2.2 Be VERY careful when copying

In [61]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
y

[1, 2, 3]

## Exercise 1 :  Total recall?

|**Term**|**Brief Description**|
|:--|:-:|
|Subsetting|Ways to *selecting* data stored in either an array or a list|
|Indexing|A way of subsetting which specifically targets a specific data point *(element)*|
|Slicing|A method of *selecting a range of elements*|
|Masking|A method of demonstrating data using a conditional which returns T/F values that hide the correct (True) values|

## Exercise 2 :  Show me the ‘odd’ letters

In [62]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [82]:
new = np_array_2d[0:,0]
new = new.astype(int)
new1 = new % 2

np_array_2d[new1> 0][0:, 1]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')